export {SearchPanel} from './SearchPanel/SearchPanel'
export {Logo} from './Logo/Logo'
export {HashTags} from './HashTags/HashTags'
export {CourseRating} from './CourseRating/CourseRating'
export {CourseGallery} from './CourseGallery/CourseGallery'
export {Duration as CourseDuration} from './Duration/Duration'
export {CourseCard} from './CourseCard/CourseCard'
export {CourseStatus} from './CourseStatus/CourseStatus'
export {CourseInfo} from './CourseInfo/CourseInfo'
export {SkillsBlock} from './SkillsBlock/SkillsBlock'
export {LessonCard} from './LessonCard/LessonCard'